exec-once = $terminal
exec-once = nm-applet &
exec-once = systemctl --user start hyprpolkitagent
exec-once = waypaper --restore
exec-once = hyprpm reload
exec-once = kbuildsycoca6
exec-once = wl-paste --type text --watch cliphist store # Stores only text data
exec-once = wl-paste --type image --watch cliphist store # Stores only image data
exec-once = hypridle
exec-once = waybar -c /home/k166/.config/waybar/blur166/config.jsonc -s /home/k166/.config/waybar/blur166/style.css
