$terminal = kitty
$fileManager = dolphin
$menu = rofi -show drun -modi "drun,run,ssh" -theme ~/.config/rofi/themes/glass.rasi  
$clip = rofi -show drun -modi "drun,run,ssh" -theme ~/.config/rofi/themes/glass.rasi
$mainMod = SUPER
env = HYPRCURSOR_THEME, Moga-Candy-Black
env = HYPRCURSOR_SIZE,12
env = QT_QPA_PLATFORMTHEME,qt6ct
env = XDG_MENU_PREFIX,arch-
env = QT_QPA_PLATFORM,wayland
env = QT_QPA_PLATFORM,wayland;xcb
env = GTK_THEME,Adwaita:dark
plugin {
    hyprscroller {        # ← era hyprscrolling
        column_width = 0.7
        fullscreen_on_one_column = false
    }
}
