source = ~/.config/hypr/monitors.conf
source = ~/.config/hypr/blur166/autoruns.conf
source = ~/.config/hypr/blur166/environment.conf
source = ~/.config/hypr/blur166/permission.conf
source = ~/.config/hypr/blur166/input.conf
source = ~/.config/hypr/blur166/keybinds.conf
source = ~/.config/hypr/blur166/windows.conf
source = ~/.cache/wal/colors-hyprland.conf

