general {
    lock_cmd = ~/lock.sh
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = hyprctl dispatch dpms on  # Liga a tela ao voltar
}

# ESTÁGIO 1: Diminuir o brilho (Aviso)
listener {
    timeout = 150                                # 2.5 minutos
    on-timeout = brightnessctl -s set 10%        # Guarda o brilho atual e baixa pra 10%
    on-resume = brightnessctl -r                 # Restaura o brilho ao mexer o mouse
}

# ESTÁGIO 2: Bloquear a tela
listener {
    timeout = 600                                # 10 minutos
    on-timeout = loginctl lock-session
}

# ESTÁGIO 3: Desligar o monitor (Economia de energia)
listener {
    timeout = 1200                                # 20 minutos
    on-timeout = hyprctl dispatch dpms off       # Desliga o monitor
    on-resume = hyprctl dispatch dpms on         # Liga ao voltar
}
